// web/src/shared/components/MermaidDiagram.tsx
import mermaid from "mermaid";
import { memo, useEffect, useId, useMemo, useState } from "react";

mermaid.initialize({
  startOnLoad: false,
  securityLevel: "strict",
  theme: "base",
  suppressErrorRendering: true,
  themeVariables: {
    primaryColor: "#0d252d",
    primaryTextColor: "#edf7f8",
    primaryBorderColor: "#49c9d8",
    lineColor: "#77e4ed",
    secondaryColor: "#122a3b",
    tertiaryColor: "#10171d",
    noteBkgColor: "#302718",
    noteTextColor: "#fff4d7",
  },
});

export const MermaidDiagram = memo(function MermaidDiagram({ source }: { source: string }) {
  const reactId = useId();
  const renderId = useMemo(() => `mermaid-${reactId.replace(/[^a-zA-Z0-9_-]/g, "")}`, [reactId]);
  const [result, setResult] = useState<{ svg: string } | { error: string } | null>(null);

  useEffect(() => {
    let canceled = false;
    setResult(null);
    mermaid.render(renderId, source).then(({ svg }) => {
      if (!canceled) setResult({ svg });
    }).catch((error: unknown) => {
      if (!canceled) setResult({ error: error instanceof Error ? error.message : String(error) });
    });
    return () => { canceled = true; };
  }, [renderId, source]);

  if (result && "error" in result) {
    return (
      <div className="mermaid-diagram mermaid-diagram-error" title={result.error}>
        <div className="mermaid-error-label">Mermaid render failed</div>
        <pre><code className="language-mermaid">{source}</code></pre>
      </div>
    );
  }

  return (
    <div
      className="mermaid-diagram"
      aria-busy={!result}
      aria-label="Mermaid diagram"
      dangerouslySetInnerHTML={result && "svg" in result ? { __html: result.svg } : undefined}
    />
  );
});

// docs/.vitepress/theme/MermaidDiagram.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import mermaid from 'mermaid'

const props = defineProps<{ code: string }>()
const html = ref('')
const error = ref('')

function source() {
  return decodeURIComponent(props.code)
}

mermaid.initialize({
  startOnLoad: false,
  securityLevel: 'loose',
  theme: 'dark',
  flowchart: {
    htmlLabels: true,
    padding: 14,
    nodeSpacing: 42,
    rankSpacing: 48
  },
  themeVariables: {
    primaryColor: '#151f2e',
    primaryTextColor: '#f8fafc',
    primaryBorderColor: '#dc1f2d',
    lineColor: '#8fb9bd',
    secondaryColor: '#172536',
    tertiaryColor: '#0b1018'
  }
})

async function renderDiagram() {
  error.value = ''
  try {
    const id = `mermaid-${Math.random().toString(36).slice(2)}`
    const result = await mermaid.render(id, source())
    html.value = result.svg
  } catch (err) {
    html.value = ''
    error.value = err instanceof Error ? err.message : String(err)
  }
}

onMounted(renderDiagram)
watch(() => props.code, renderDiagram)
</script>

<template>
  <div class="v3-mermaid">
    <div v-if="html" v-html="html" />
    <pre v-else class="v3-mermaid-error"><code>{{ error || source() }}</code></pre>
  </div>
</template>
